### ISSUE TITLE
Enchant mh weapon placement

### ISSUE THREAD

**Issue by E-Tsx** [Repooc/ElvUI_WrathArmory#1]
DK runeforge enchant currently goes outside the window on longer names. (on unadjusted default profile) 
![image](https://user-images.githubusercontent.com/97974579/192128810-18c62982-0dc0-4fad-9aaa-363af203845d.png)

**Comment by Repooc** [comment]
default profile is not an end all, you are free to adjust as you see fit.  I do plan on implementing a way to alter the text (so you can make it shorter if you want).

**Comment by Repooc** [comment]
if u have a better layout that would work generally well for everything, get the values to me for each option (pictures would work)
