### ISSUE TITLE
Covers Gearquipper addon

### ISSUE THREAD

**Issue by seathasky** [Repooc/ElvUI_WrathArmory#10]
![image](https://user-images.githubusercontent.com/17598024/194713344-43991ec3-012d-4ac1-8297-1d3bc77f4dc3.png)

Any way to allow other addons to go over the ilvl panel? Addons like "Gear Quipper" (Better equipment manager addon) are now unusable.

Great plugin for elvui otherwise!

**Comment by Repooc** [comment]
#8 will solve this

**Comment by seathasky** [comment]
> #8 will solve this

Any progress on this yet? Really would love to use your addon

**Comment by Repooc** [comment]
no just havent had time to sit down and give it much time

**Comment by seathasky** [comment]
No worries, thanks for the response!
