### ISSUE TITLE
Missing enchant IDs - engineering tinkers

### ISSUE THREAD

**Issue by Lueron** [Repooc/ElvUI_WrathArmory#19]
These engineering tinker IDs appear to be missing.
3606
Nitro Boosts to boots https://www.wowhead.com/wotlk/spell=55016/nitro-boosts

3604
Hyperspeed Accelerators to gloves https://www.wowhead.com/wotlk/spell=54999/hyperspeed-accelerators

**Comment by Repooc** [comment]
guess u didnt update and/or read the closed tickets?

**Comment by Lueron** [comment]
> 

I have updated, I am on 1.02, I am still getting the IDs missing even though I can see them in the db file and the previous commits (which admittedly I did not check as I assumed updating would be enough).

![image](https://user-images.githubusercontent.com/28562588/195001462-cf197ed8-afa4-4a80-8de3-71d62e23f4b1.png)

**Comment by Malpractis** [comment]
The engineering tinkers have been working for me w/o issue. Maybe try a reinstall?

**Comment by Repooc** [comment]
Yeah there should be no way in that version for it to fail unless you have the same library in a different adding that is taking priority.  Shouldn't be possible the way I did it but I can change it more to fully ensure it doesn't try to pull from the other library version.  If you install manually,  make sure to delete the addon folder first and not drag over and overwrite as sometimes that fails
