### ISSUE TITLE
Suggestion: Show missing enchants

### ISSUE THREAD

**Issue by MattZeeX** [Repooc/ElvUI_WrathArmory#25]
It seems like you're already planning to include this, since you've opened issues for yourself for missing hunter scopes and belt buckles, but I guess I just wanted to 'suggest' that you add an indicator that an item can be enchanted and is currently not enchanted. I got this addon because it is similar to the armory plugin provided by Shadow and Light on retail, and in S&L it shows some red text saying "missing enchant" or something on items that aren't enchanted. This would be helpful to remind me to enchant my gear in my offspec set that I sometimes forget.

Perhaps an option to enable showing caution text in yellow when using not the highest "rank" of an enchant (where applicable) say major stats instead of powerful stats on chest. Or alternatively, allowing the "quality color" checkbox for enchants to instead colour them purple (epic) for the highest level enchants, blue (rare) for the 2nd best or lower quality WOTLK versions, and then green (uncommon) for all other lower rank enchants.

Love the addon, thank you!

**Comment by Repooc** [comment]
> It seems like you're already planning to include this, since you've opened issues for yourself for missing hunter scopes and belt buckles, but I guess I just wanted to 'suggest' that you add an indicator that an item can be enchanted and is currently not enchanted. I got this addon because it is similar to the armory plugin provided by Shadow and Light on retail, and in S&L it shows some red text saying "missing enchant" or something on items that aren't enchanted. This would be helpful to remind me to enchant my gear in my offspec set that I sometimes forget.
> 
> Perhaps an option to enable showing caution text in yellow when using not the highest "rank" of an enchant (where applicable) say major stats instead of powerful stats on chest. Or alternatively, allowing the "quality color" checkbox for enchants to instead colour them purple (epic) for the highest level enchants, blue (rare) for the 2nd best or lower quality WOTLK versions, and then green (uncommon) for all other lower rank enchants.
> 
> Love the addon, thank you!

i have pushed a somewhat basic indicator to signal missing enchant, missing belt buckle, or not having all gems socketed.

**Comment by MattZeeX** [comment]
Thank you!

**Comment by Repooc** [comment]
i will eventually give it some more customization but figured i would get something pushed for people that use git to try it before i release.... plus im going out of town in a couple days, so didnt want to push a release and have issues arise bc of the changes and not really have easy access to make changes... well test those changes really.
