### ISSUE TITLE
Missing +30 Intellect to 1hand

### ISSUE THREAD

**Issue by seathasky** [Repooc/ElvUI_WrathArmory#26]
![image](https://user-images.githubusercontent.com/17598024/197190583-ba203271-9f58-444e-92bb-9b2e60f768dc.png)
Missing Intellect to 1h enchant on latest update prep 1.0.4. 
This enchant showed in previous versions of your add-on.

**Comment by Repooc** [comment]
Nothing that regards should have changed.  Are you getting any messages in chat about it missing as u didn't specify that

**Comment by seathasky** [comment]
No idea, I can install the old one to show you if you need. No messages in chat or anything that i've seen.

**Comment by Repooc** [comment]
are you in tukui/elvui discord? if so, there is a thread for wratharmory there if u can ping me there or i can give u a link to the discord or something

**Comment by Repooc** [comment]
Repooc#2655 in the Tukui Community discord. 
Server Invite just in case: https://discord.gg/xFWcfgE
Link directly to the thread I was referring to: https://discord.com/channels/209244641537556480/1022792365150306374
