### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Tatharia** [Repooc/ElvUI_WrathArmory#28]
Im running ElvUI 13.20.
Since updating the new "fixed" version of WrathArmory, WrathArmory is not loaded as a plugin in Elvui.

![image](https://user-images.githubusercontent.com/110652776/213342736-1c51cff4-32e9-41d5-b639-0c4d067e69a8.png)

**Comment by PartyPlatypus** [comment]
Not loading for me as an elv pluigin

**Comment by Repooc** [comment]
you should be testing with just ElvUI, ElvUI_Libraries, ElvUI_Options and WrathArmory and not with other addons that may be breaking the addon

**Comment by Tatharia** [comment]
I found the culprit. its Elv UI Group Finder Data Text plugin. Disabling seems to load wrath armory properly
