### ISSUE TITLE
Add option to enable gearscore instead of ilvl

### ISSUE THREAD

**Issue by AddAndy** [Repooc/ElvUI_WrathArmory#29]
most people are asking about Gearscore not ilvl. could you add an option to show gearscore as part of the armory ui?

**Comment by mnejing** [comment]
https://github.com/mnejing/ElvUI-WrathArmory-with-GearScore

I'm reaching out to Repooc on Discord to see if this is something he wants. In the meantime, this is my modified repo that contains GearScore as well as item level.

**Comment by Repooc** [comment]
dont fork my stuff to distribute, u can do a pr if u made changes and ill merge them if they are fine and i agree with the changes.

**Comment by Repooc** [comment]
i also dont accept blind friend requests which i pinged u in the elvui discord wondering why you sent the request in the first place as i just now checked my email and seen this reply.  i just dont have time to test and such and deal with irl stuff. so if u do a pull request it will get added faster... and if u dont mind linking the addon(s) people are using to get the gearscore value

**Comment by mnejing** [comment]
That's fine, someone else is welcome to do it.

**Comment by mnejing** [comment]
Further, you have an attitude problem. I suspect it's ego-related.

**Comment by Azilroka** [comment]
> Further, you have an attitude problem.

Not really. It's not ego related either.

He just prefers the actual pull request instead of someone distributing his code with modified changes then get someone in his support asking for help and it's not his code. 

It's wasted time in troubleshooting an issue that wasn't his to begin with.

**Comment by chedster** [comment]
Hey @Repooc, I just found this library for calculating the gearscore: https://www.curseforge.com/wow/addons/libgearscore

Would this be something that you're comfortable building in to this plugin to calculate the gearscore? I've already verified that the formula that it's using is the same as the one that is used in TacoTip (the addon everyone uses to view gearscore currently)

If this is something that you're comfortable with, I can look into adding it and submitting a PR.

**Comment by chedster** [comment]
Created a PR here: https://github.com/Repooc/ElvUI_WrathArmory/pull/33. It won't let me link this issue to that PR though :/

**Comment by Repooc** [comment]
> Further, you have an attitude problem.

See, they took the time to do a pr for something I didn't really care to do or not. I even accepted it as it seems like the pr was in good shape. Just needs some testing and I'll push it live.

If any issues with the pr changes, people can open a new ticket or come to the discord I have for my plugins at http://repoocreforged.dev/discord
