### ISSUE TITLE
Shorten Enchant Letters

### ISSUE THREAD

**Issue by Melocide** [Repooc/ElvUI_WrathArmory#35]
is it probably doable to Shorten Enchants? Like Stamina to "Stam" ; "Agi" for Agility etc. because some Enchants have really much letters so they crash into the other enchants e.g Shoulder Enchant "30stam +15res" is so long that it collides with the leg enchant "55stam & 22agi"

**Comment by Repooc** [comment]
duplicate of #12 
Yeah I have been pretty busy, I will see about implementing the idea I have end of the week...it something that I have done something similar in another addon of mine before, so shouldnt take to long actually
