### ISSUE TITLE
BUG: Possible conflict with TSM

### ISSUE THREAD

**Issue by newbCoder-git** [Repooc/ElvUI_WrathArmory#36]
It seems only to happen (or more frequently for me to notice) when I do the daily quest "Break the blockade".
This error pops up when I'm throwing the bombs down

I say this is a TSM conflict error only due to the fact that TSM is written in the error

If I notice it in other places, I will update

Message: Interface_Wrath/FrameXML/WatchFrame.lua:1212: attempt to compare number with nil
Time: Fri Jan 12 11:10:32 2024
Count: 2
Stack: Interface_Wrath/FrameXML/WatchFrame.lua:1212: attempt to compare number with nil
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface_Wrath/FrameXML/WatchFrame.lua"]:1212: in function `WatchFrameItem_UpdateCooldown'
[string "@Interface_Wrath/FrameXML/WatchFrame.lua"]:1227: in function `WatchFrameItem_OnEvent'
[string "*WatchFrame.xml:67_OnEvent"]:1: in function <[string "*WatchFrame.xml:67_OnEvent"]:1>

**Comment by Repooc** [comment]
i am not sure why you posted here, i do not touch the watch frame and doesnt mention my addon at all nor any code my addon touches
